-- 코드를 입력하세요
-- SELECT book_id, sales_date, sales
-- from book_sales
-- where to_char(sales_date,'YYYY-MM') = '2022-01'
-- group by book_id;

SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
, SUM(BOOK_SALES.SALES*BOOK.PRICE) AS TOTAL_SALE
FROM BOOK
INNER JOIN BOOK_SALES
ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
INNER JOIN AUTHOR
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE TO_CHAR(BOOK_SALES.SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC;
