-- 코드를 입력하세요
SELECT CATEGORY, PRICE as MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE 1=1 
    AND (CATEGORY,PRICE) IN (
        SELECT CATEGORY, MAX(PRICE) as PRICE
            FROM FOOD_PRODUCT
            WHERE CATEGORY in ('과자', '국', '김치', '식용유')
            GROUP BY CATEGORY
    )
ORDER BY PRICE DESC;

