-- 코드를 입력하세요
SELECT R.PRODUCT_ID, R.PRODUCT_NAME, SUM(PRICE * AMOUNT) AS TOTAL_SALES
  FROM FOOD_PRODUCT R
     , FOOD_ORDER   D
 WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
   AND R.PRODUCT_ID = D.PRODUCT_ID
 GROUP BY R.PRODUCT_ID, PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, R.PRODUCT_ID