SELECT BK.BOOK_ID, AU.AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d')
  FROM BOOK BK, AUTHOR AU
  WHERE BK.AUTHOR_ID = AU.AUTHOR_ID AND BK.CATEGORY = '경제'
  ORDER BY DATE_FORMAT(PUBLISHED_DATE,'%Y-%m-%d') ASC;