-- 코드를 입력하세요
SELECT a.REST_ID, a.REST_NAME, a.FOOD_TYPE, a.FAVORITES, a.ADDRESS, ROUND(avg(REVIEW_SCORE),2) as SCORE
FROM REST_INFO a, REST_REVIEW b
WHERE a.REST_ID = b.REST_ID AND ADDRESS LIKE '서울%'
group by REST_ID
order by SCORE desc, FAVORITES desc;